import '../utils/price_utils.dart';

class ProductDataService {
  static List<Map<String, dynamic>> getAllProducts() {
    return [
      ...getCepillosProducts(),
      ...getCremasProducts(),
      ...getEnjuaguesProducts(),
      ...getSedasProducts(),
      ...getUniversoNinosProducts(),
      ...getKitsProducts(),
    ];
  }

  static List<Map<String, dynamic>> getCepillosProducts() {
    return [
      {
        'title': 'Cepillo Dental Original Ristro',
        'price': PriceUtils.formatPriceDisplay('14109'),
        'image': 'assets/CEPILLOS/RISTRACEPILLO.png',
        'rating': '5.0',
        'description':
            'Mango ergonmico que se adapta perfectamente a tu mano con inclinacin en forma de espejo odontolgico para llegar fcil a todas las dentaduras.',
        'codigoSap': '50360251',
        'codigoSapSuave': '50360256',
        'textura': 'Media',
        'hasTextureOptions': true,
        'category': 'Cepillos',
        'disponible': true,
        'mensajeEstado': 'Producto disponible',
        'features': ['Cerdas ultra suaves', 'Mango ergonmico', 'Tecnologa avanzada', 'Cuidado de encas'],
        'specifications': {'Material': 'Nylon de alta calidad', 'Dureza': 'Suave'}
      },
      {
        'title': 'Cep Original Flex Ristra x12',
        'price': PriceUtils.formatPriceDisplay('16983'),
        'image': 'assets/CEPILLOS/RISTRACEPILLORIGINAL12.png',
        'rating': '5.0',
        'description': 'Cepillo premium con cerdas extra suaves y cabezal compacto',
        'codigoSap': '50360249',
        'codigoSapSuave': '50360250',
        'textura': 'Media',
        'hasTextureOptions': true,
        'category': 'Cepillos',
        'disponible': true,
        'mensajeEstado': 'Producto disponible',
        'features': ['Cerdas premium', 'Cabezal compacto', 'Mango antideslizante', 'Limpieza profunda'],
        'specifications': {'Dureza': 'Suave'}
      },
      {
        'title': 'Cepillo Original',
        'price': PriceUtils.formatPriceDisplay('1280'),
        'image': 'assets/CEPILLOS/ORIGINAL.png',
        'rating': '5.0',
        'description': 'Cerdas de dureza media para limpieza efectiva diaria',
        'codigoSap': '50360264',
        'codigoSapSuave': '50360267',
        'textura': 'Media',
        'hasTextureOptions': true,
        'category': 'Cepillos',
        'disponible': true,
        'mensajeEstado': 'Producto disponible',
        'features': ['Cerdas medias', 'Limpieza efectiva', 'Diseo ergonmico', 'Uso diario'],
        'specifications': {'Dureza': 'Media', 'Tamao': 'Estndar'}
      },
      {
        'title': 'Cepillo Ultra Duo Individual',
        'price': PriceUtils.formatPriceDisplay('5072'),
        'image': 'assets/CEPILLOS/CEPILLOULTRAINDIVIDUAL.png',
        'rating': '5.0',
        'description': 'Cepillo compacto ideal para viajes con estuche protector',
        'codigoSap': '50280060',
        'codigoSapSuave': '50280095',
        'textura': 'Media',
        'hasTextureOptions': true,
        'category': 'Cepillos',
        'disponible': true,
        'mensajeEstado': 'Producto disponible',
        'features': ['Tamao compacto', 'Estuche incluido', 'Porttil', 'Cerdas suaves'],
        'specifications': {'Dureza': 'Suave'}
      },
      {
        'title': 'Cepillo Ultra Individual',
        'price': PriceUtils.formatPriceDisplay('2930'),
        'image': 'assets/CEPILLOS/CEPILLOULTRADUOSUAVE.png',
        'rating': '5.0',
        'description': 'Cepillo ecolgico con mango de bamb y cerdas naturales',
        'codigoSap': '50360084',
        'codigoSapSuave': '50290044',
        'textura': 'Media',
        'hasTextureOptions': true,
        'category': 'Cepillos',
        'disponible': true,
        'mensajeEstado': 'Producto disponible',
        'features': ['Mango de bamb', 'Cerdas naturales', 'Biodegradable', 'Eco-friendly'],
        'specifications': {'Material': 'Bamb natural', 'Dureza': 'Suave', 'Tamao': 'Estndar'}
      },
      {
        'title': 'Cepillo Waviness',
        'price': PriceUtils.formatPriceDisplay('1685'),
        'image': 'assets/CEPILLOS/CEPILLOWAVINES.png',
        'rating': '5.0',
        'description': 'Diseo especial para limpieza con brackets y aparatos ortodnticos',
        'codigoSap': '50360167',
        'textura': 'Media',
        'category': 'Cepillos',
        'disponible': true,
        'mensajeEstado': 'Producto disponible',
        'features': ['Diseo ortodntico', 'Limpieza brackets', 'Cerdas especiales', 'Acceso fcil'],
        'specifications': {'Material': 'Nylon especializado', 'Dureza': 'Suave'}
      },
      {
        'title': 'Ristra Cepillo Waviness X12',
        'price': PriceUtils.formatPriceDisplay('19674'),
        'image': 'assets/CEPILLOS/RISTRAWAVINESS12.png',
        'rating': '5.0',
        'description': 'Diseo especial para limpieza con brackets y aparatos ortodnticos',
        'codigoSap': '50360243',
        'textura': 'Media',
        'category': 'Cepillos',
        'disponible': true,
        'mensajeEstado': 'Producto disponible',
        'features': ['Diseo ortodntico', 'Limpieza brackets', 'Cerdas especiales', 'Acceso fcil'],
        'specifications': {'Material': 'Nylon especializado', 'Dureza': 'Media'}
      },
      {
        'title': 'Cepillo Calipso Ind',
        'price': PriceUtils.formatPriceDisplay('3220'),
        'image': 'assets/CEPILLOS/CEPILLOWAVINES.png',
        'rating': '5.0',
        'description': 'Diseo especial para limpieza con brackets y aparatos ortodnticos',
        'codigoSap': '50280124',
        'codigoSapSuave': '50290044',
        'textura': 'Media',
        'hasTextureOptions': true,
        'category': 'Cepillos',
        'disponible': true,
        'mensajeEstado': 'Producto disponible',
        'features': ['Diseo ortodntico', 'Limpieza brackets', 'Cerdas especiales', 'Acceso fcil'],
        'specifications': {'Material': 'Nylon especializado', 'Dureza': 'Suave'}
      },
      {
        'title': 'Kit Calipso',
        'price': PriceUtils.formatPriceDisplay('5487'),
        'image': 'assets/CEPILLOS/CALIPSO3.png',
        'rating': '5.0',
        'description': 'Diseo especial para limpieza con brackets y aparatos ortodnticos',
        'codigoSap': '50280128',
        'textura': 'Media',
        'category': 'Cepillos',
        'disponible': true,
        'mensajeEstado': 'Producto disponible',
        'features': ['Diseo ortodntico', 'Limpieza brackets', 'Cerdas especiales', 'Acceso fcil'],
        'specifications': {'Material': 'Nylon especializado', 'Dureza': 'Suave'}
      },
      {
        'title': 'Cepillo Calipso X3',
        'price': PriceUtils.formatPriceDisplay('3220'),
        'image': 'assets/CEPILLOS/CALIPSO3.png',
        'rating': '5.0',
        'description': 'Diseo especial para limpieza con brackets y aparatos ortodnticos',
        'codigoSap': '50280126',
        'codigoSapSuave': '50280127',
        'textura': 'Media',
        'hasTextureOptions': true,
        'category': 'Cepillos',
        'disponible': true,
        'mensajeEstado': 'Producto disponible',
        'features': ['Diseo ortodntico', 'Limpieza brackets', 'Cerdas especiales', 'Acceso fcil'],
        'specifications': {'Material': 'Nylon especializado', 'Dureza': 'Suave'}
      },
      {
        'title': 'Cepillo Calipso x5',
        'price': PriceUtils.formatPriceDisplay('3220'),
        'image': 'assets/CEPILLOS/CALIPSO5.png',
        'rating': '5.0',
        'description': 'Diseo especial para limpieza con brackets y aparatos ortodnticos',
        'codigoSap': '50360072',
        'textura': 'Media',
        'category': 'Cepillos',
        'disponible': true,
        'mensajeEstado': 'Producto disponible',
        'features': ['Diseo ortodntico', 'Limpieza brackets', 'Cerdas especiales', 'Acceso fcil'],
        'specifications': {'Material': 'Nylon especializado', 'Dureza': 'Suave'}
      },
      {
        'title': 'Cepillo Dakota',
        'price': PriceUtils.formatPriceDisplay('3220'),
        'image': 'assets/CEPILLOS/CEPILLODACOTA.png',
        'rating': '5.0',
        'description': 'Diseo especial para limpieza con brackets y aparatos ortodnticos',
        'codigoSap': '50280118',
        'textura': 'Media',
        'category': 'Cepillos',
        'disponible': true,
        'mensajeEstado': 'Producto disponible',
        'features': ['Diseo ortodntico', 'Limpieza brackets', 'Cerdas especiales', 'Acceso fcil'],
        'specifications': {'Material': 'Nylon especializado', 'Dureza': 'Suave'}
      },
      {
        'title': 'Kit Dakota',
        'price': PriceUtils.formatPriceDisplay('8106'),
        'image': 'assets/KITS/KITDACOTA.png',
        'rating': '5.0',
        'description': 'Diseo especial para limpieza con brackets y aparatos ortodnticos',
        'codigoSap': '50280122',
        'textura': 'Media',
        'category': 'Cepillos',
        'disponible': true,
        'mensajeEstado': 'Producto disponible',
        'features': ['Diseo ortodntico', 'Limpieza brackets', 'Cerdas especiales', 'Acceso fcil'],
        'specifications': {'Material': 'Nylon especializado', 'Dureza': 'Suave'}
      },
      {
        'title': 'Cepillo Duo Dakota',
        'price': PriceUtils.formatPriceDisplay('6107'),
        'image': 'assets/CEPILLOS/CEPILLODUODACOTA.png',
        'rating': '5.0',
        'description': 'Diseo especial para limpieza con brackets y aparatos ortodnticos',
        'codigoSap': '50280116',
        'textura': 'Media',
        'category': 'Cepillos',
        'disponible': true,
        'mensajeEstado': 'Producto disponible',
        'features': ['Diseo ortodntico', 'Limpieza brackets', 'Cerdas especiales', 'Acceso fcil'],
        'specifications': {'Material': 'Nylon especializado', 'Dureza': 'Suave'}
      },
      {
        'title': 'Cepillo Model 400 Ind',
        'price': PriceUtils.formatPriceDisplay('3789'),
        'image': 'assets/CEPILLOS/CEPILLOMODEL400.png',
        'rating': '5.0',
        'description': 'Diseo especial para limpieza con brackets y aparatos ortodnticos',
        'codigoSap': '50360465',
        'codigoSapSuave': '50360464',
        'textura': 'Media',
        'hasTextureOptions': true,
        'category': 'Cepillos',
        'disponible': true,
        'mensajeEstado': 'Producto disponible',
        'features': ['Diseo ortodntico', 'Limpieza brackets', 'Cerdas especiales', 'Acceso fcil'],
        'specifications': {'Material': 'Nylon especializado', 'Dureza': 'Suave'}
      },
      {
        'title': 'Cepillo Model 400 X3',
        'price': PriceUtils.formatPriceDisplay('9661'),
        'image': 'assets/CEPILLOS/CEPILLOMODEL4003.png',
        'rating': '5.0',
        'description': 'Diseo especial para limpieza con brackets y aparatos ortodnticos',
        'codigoSap': '50360467',
        'codigoSapSuave': '50360466',
        'textura': 'Media',
        'hasTextureOptions': true,
        'category': 'Cepillos',
        'disponible': true,
        'mensajeEstado': 'Producto disponible',
        'features': ['Diseo ortodntico', 'Limpieza brackets', 'Cerdas especiales', 'Acceso fcil'],
        'specifications': {'Material': 'Nylon especializado', 'Dureza': 'Suave'}
      },
      {
        'title': 'Cepillo Model 400 X5',
        'price': PriceUtils.formatPriceDisplay('15154'),
        'image': 'assets/CEPILLOS/CEPILLOMODEL4005.png',
        'rating': '5.0',
        'description': 'Diseo especial para limpieza con brackets y aparatos ortodnticos',
        'codigoSap': '50360469',
        'codigoSapSuave': '50360468',
        'textura': 'Media',
        'hasTextureOptions': true,
        'category': 'Cepillos',
        'disponible': true,
        'mensajeEstado': 'Producto disponible',
        'features': ['Diseo ortodntico', 'Limpieza brackets', 'Cerdas especiales', 'Acceso fcil'],
        'specifications': {'Material': 'Nylon especializado', 'Dureza': 'Suave'}
      },
      {
        'title': 'Cepillo Cuidado Total',
        'price': PriceUtils.formatPriceDisplay('6401'),
        'image': 'assets/CEPILLOS/CEPILLOCUIDADOTOTAL.png',
        'rating': '5.0',
        'description': 'Diseo especial para limpieza con brackets y aparatos ortodnticos',
        'codigoSap': '50280022',
        'codigoSapSuave': '50360468',
        'textura': 'Media',
        'hasTextureOptions': true,
        'category': 'Cepillos',
        'disponible': true,
        'mensajeEstado': 'Producto disponible',
        'features': ['Diseo ortodntico', 'Limpieza brackets', 'Cerdas especiales', 'Acceso fcil'],
        'specifications': {'Material': 'Nylon especializado', 'Dureza': 'Suave'}
      },
      {
        'title': 'Cepillo Cuidado Total X2',
        'price': PriceUtils.formatPriceDisplay('10111'),
        'image': 'assets/CEPILLOS/CEPILLOCUIDADOTOTAL2.png',
        'rating': '5.0',
        'description': 'Diseo especial para limpieza con brackets y aparatos ortodnticos',
        'codigoSap': '50280026',
        'textura': 'Media',
        'category': 'Cepillos',
        'disponible': true,
        'mensajeEstado': 'Producto disponible',
        'features': ['Diseo ortodntico', 'Limpieza brackets', 'Cerdas especiales', 'Acceso fcil'],
        'specifications': {'Material': 'Nylon especializado', 'Dureza': 'Suave'}
      },
      {
        'title': 'Cepillo Cuidado Total X3',
        'price': PriceUtils.formatPriceDisplay('13913'),
        'image': 'assets/CEPILLOS/CEPILLOCUIDADOTOTAL3.png',
        'rating': '5.0',
        'description': 'Diseo especial para limpieza con brackets y aparatos ortodnticos',
        'codigoSap': '50360238',
        'textura': 'Media',
        'category': 'Cepillos',
        'disponible': true,
        'mensajeEstado': 'Producto disponible',
        'features': ['Diseo ortodntico', 'Limpieza brackets', 'Cerdas especiales', 'Acceso fcil'],
        'specifications': {'Material': 'Nylon especializado', 'Dureza': 'Suave'}
      },
    ];
  }

  static List<Map<String, dynamic>> getCremasProducts() {
    return [
      {
        'title': 'Cremas Dental Cool Mint 30g',
        'price': PriceUtils.formatPriceDisplay('2554'),
        'image': 'assets/CREMAS/COOLMINT30.png',
        'rating': '5.0',
        'description': 'Cuida tu salud bucal con un sabor fresco y natural',
        'codigoSap': '50340010',
        'category': 'Cremas',
        'disponible': true,
        'mensajeEstado': 'Producto disponible',
        'features': ['Sin qumicos dainos', 'Sabor neutro'],
        'specifications': {'Contenido': '30g'}
      },
      {
        'title': 'Cremas Dental Cool Mint 70g',
        'price': PriceUtils.formatPriceDisplay('2743'),
        'image': 'assets/CREMAS/COOLMINT70.png',
        'rating': '5.0',
        'description': 'Cuida tu salud bucal con un sabor fresco y natural',
        'codigoSap': '50340012',
        'category': 'Cremas',
        'disponible': true,
        'mensajeEstado': 'Producto disponible',
        'features': ['Sin qumicos dainos', 'Sabor neutro'],
        'specifications': {'Contenido': '70g'}
      },
      {
        'title': 'Cremas Dental Cool Mint 120g',
        'price': PriceUtils.formatPriceDisplay('5160'),
        'image': 'assets/CREMAS/COLMINT90.png',
        'rating': '5.0',
        'description': 'Cuida tu salud bucal con un sabor fresco y natural',
        'codigoSap': '50340025',
        'category': 'Cremas',
        'disponible': true,
        'mensajeEstado': 'Producto disponible',
        'features': ['Alivio sensibilidad', 'Fmula suave', 'Sin abrasivos'],
        'specifications': {'Contenido': '120g'}
      },
      {
        'title': 'Cremas Dental Cool Mint 7g + cepillo + protector',
        'price': PriceUtils.formatPriceDisplay('4248'),
        'image': 'assets/CREMAS/COOLMINTCREMA.png',
        'rating': '4.7',
        'description': 'Fmula natural con extractos herbales para cuidado integral',
        'codigoSap': '50360371',
        'category': 'Cremas',
        'disponible': true,
        'mensajeEstado': 'Producto disponible',
        'features': ['Extractos naturales', 'Sin qumicos', 'Cuidado integral', 'Sabor herbal'],
        'specifications': {'Contenido': 'Cremas Dental Cool Mint 7g + cepillo + protector'}
      },
      {
        'title': 'Cremas Dental En Gel Cuidado Total 30g',
        'price': PriceUtils.formatPriceDisplay('3053'),
        'image': 'assets/CREMAS/TOTAL30.png',
        'rating': '5.0',
        'description': 'Cuida tu salud bucal con un sabor fresco y natural',
        'codigoSap': '50360074',
        'category': 'Cremas',
        'disponible': true,
        'mensajeEstado': 'Producto disponible',
        'features': ['Proteccin anticaries', 'Fortalece esmalte', 'Sabor fresco'],
        'specifications': {'Contenido': '30g'}
      },
      {
        'title': 'Cremas Dental En Gel Cuidado Total 70g',
        'price': PriceUtils.formatPriceDisplay('4593'),
        'image': 'assets/CREMAS/TOTAL70.png',
        'rating': '5.0',
        'description': 'Cuida tu salud bucal con un sabor fresco y natural',
        'codigoSap': '50360076',
        'category': 'Cremas',
        'disponible': true,
        'mensajeEstado': 'Producto disponible',
        'features': ['Cuidado 5 en 1', 'Blanquea y protege', 'Fortalece encas', 'Aliento fresco'],
        'specifications': {'Contenido': '70g'}
      },
      {
        'title': 'Cremas Dental En Gel Cuidado Total 90g',
        'price': PriceUtils.formatPriceDisplay('6150'),
        'image': 'assets/CREMAS/TOTAL90.png',
        'rating': '5.0',
        'description': 'Cuida tu salud bucal con un sabor fresco y natural',
        'codigoSap': '50360137',
        'category': 'Cremas',
        'disponible': true,
        'mensajeEstado': 'Producto disponible',
        'features': ['Cuidado 5 en 1', 'Blanquea y protege', 'Fortalece encas', 'Aliento fresco'],
        'specifications': {'Contenido': '90g'}
      },
      {
        'title': 'Cremas Dental En Gel Carbon Activado 30g',
        'price': PriceUtils.formatPriceDisplay('5095'),
        'image': 'assets/CREMAS/CARBONACTIVADO30.png',
        'rating': '5.0',
        'description': 'Cuida tu salud bucal con un sabor fresco y natural',
        'codigoSap': '50360150',
        'category': 'Cremas',
        'disponible': true,
        'mensajeEstado': 'Producto disponible',
        'features': ['Blanquea y protege', 'Aliento fresco'],
        'specifications': {'Contenido': '30g'}
      },
      {
        'title': 'Cremas Dental En Gel Carbon Activado 70g',
        'price': PriceUtils.formatPriceDisplay('8731'),
        'image': 'assets/CREMAS/CARBONACTIVADO70.png',
        'rating': '5.0',
        'description': 'Cuida tu salud bucal con un sabor fresco y natural',
        'codigoSap': '50360152',
        'category': 'Cremas',
        'disponible': true,
        'mensajeEstado': 'Producto disponible',
        'features': ['Blanquea y protege', 'Aliento fresco'],
        'specifications': {'Contenido': '70g'}
      },
      {
        'title': 'Cremas Dental En Gel Carbon Activado 90g',
        'price': PriceUtils.formatPriceDisplay('10302'),
        'image': 'assets/CREMAS/CARBONACTIVADO90.png',
        'rating': '5.0',
        'description': 'Cuida tu salud bucal con un sabor fresco y natural',
        'codigoSap': '50360154',
        'category': 'Cremas',
        'disponible': true,
        'mensajeEstado': 'Producto disponible',
        'features': ['Cuidado 5 en 1', 'Blanquea y protege', 'Fortalece encas', 'Aliento fresco'],
        'specifications': {'Contenido': '90g'}
      },
      {
        'title': 'Cremas Dental Cuatriaccion Plus 30g',
        'price': PriceUtils.formatPriceDisplay('1416'),
        'image': 'assets/CREMAS/CUATRI30.png',
        'rating': '5.0',
        'description': 'Cuida tu salud bucal con un sabor fresco y natural',
        'codigoSap': '50360473',
        'category': 'Cremas',
        'disponible': true,
        'mensajeEstado': 'Producto disponible',
        'features': ['Cuidado 5 en 1', 'Blanquea y protege', 'Fortalece encas', 'Aliento fresco'],
        'specifications': {'Contenido': '30g'}
      },
      {
        'title': 'Cremas Dental Cuatriaccion Plus 151.2g',
        'price': PriceUtils.formatPriceDisplay('4375'),
        'image': 'assets/CREMAS/CUATRI151.png',
        'rating': '5.0',
        'description': 'Cuida tu salud bucal con un sabor fresco y natural',
        'codigoSap': '50360471',
        'category': 'Cremas',
        'disponible': true,
        'mensajeEstado': 'Producto disponible',
        'features': ['Cuidado 4 en 1', 'Blanquea y protege', 'Fortalece encas', 'Aliento fresco'],
        'specifications': {'Contenido': '151.2g'}
      },
      {
        'title': 'Cremas Dental Cuatriaccion Plus x3',
        'price': PriceUtils.formatPriceDisplay('13816'),
        'image': 'assets/CREMAS/CREMA23.png',
        'rating': '5.0',
        'description': 'Cuida tu salud bucal con un sabor fresco y natural',
        'codigoSap': '50360475',
        'category': 'Cremas',
        'disponible': true,
        'mensajeEstado': 'Producto disponible',
        'features': ['Cuidado 4 en 1', 'Blanquea y protege', 'Fortalece encas', 'Aliento fresco'],
        'specifications': {'Contenido': 'x3'}
      },
    ];
  }

  static List<Map<String, dynamic>> getEnjuaguesProducts() {
    return [
      {
        'title': 'Enjuague Bucal Caja x24',
        'price': PriceUtils.formatPriceDisplay('75327'),
        'image': 'assets/ENJUAGES/TOTALMULTIPLE.png',
        'rating': '5.0',
        'description': 'Proteccin antibacterial de 12 horas para aliento fresco',
        'codigoSap': '50360120',
        'category': 'Enjuagues',
        'disponible': true,
        'mensajeEstado': 'Producto disponible',
        'features': ['Proteccin 12 horas', 'Antibacterial', 'Aliento fresco', 'Sin alcohol'],
        'specifications': {'Contenido': 'Caja x24'}
      },
      {
        'title': 'Enjuague Bucal Cuidado Total 180ml',
        'price': PriceUtils.formatPriceDisplay('5160'),
        'image': 'assets/ENJUAGES/CUIDADOTOTAL180.png',
        'rating': '5.0',
        'description': 'Cuida tu salud bucal con un sabor fresco y natural',
        'codigoSap': '50340048',
        'category': 'Enjuagues',
        'disponible': true,
        'mensajeEstado': 'Producto disponible',
        'features': ['Antibacterial', 'Aliento fresco'],
        'specifications': {'Contenido': '180ml'}
      },
      {
        'title': 'Enjuague Bucal Cuidado Total 300ml',
        'price': PriceUtils.formatPriceDisplay('7224'),
        'image': 'assets/ENJUAGES/CUIDADOTOTAL300.png',
        'rating': '5.0',
        'description': 'Cuidado especial para dientes sensibles con alivio prolongado',
        'codigoSap': '50360087',
        'category': 'Enjuagues',
        'disponible': true,
        'mensajeEstado': 'Producto disponible',
        'features': ['Para sensibilidad', 'Alivio prolongado', 'Fmula suave', 'Sin ardor'],
        'specifications': {'Contenido': '300ml'}
      },
      {
        'title': 'Enjuague Bucal Cuidado Total 500ml',
        'price': PriceUtils.formatPriceDisplay('10114'),
        'image': 'assets/ENJUAGES/CUIDADOTOTAL500.png',
        'rating': '5.0',
        'description': 'Blanqueamiento gradual con uso diario, resultados visibles',
        'codigoSap': '50340046',
        'category': 'Enjuagues',
        'disponible': true,
        'mensajeEstado': 'Producto disponible',
        'features': ['Blanqueamiento gradual', 'Resultados visibles', 'Protege esmalte', 'Uso diario'],
        'specifications': {'Contenido': '500ml'}
      },
      {
        'title': 'Enjuague Bucal Cuidado Total 1000ml',
        'price': PriceUtils.formatPriceDisplay('15171'),
        'image': 'assets/ENJUAGES/AMARRECUIDADOTOTAL.png',
        'rating': '5.0',
        'description': 'Fmula natural con extractos de plantas medicinales',
        'codigoSap': '50340050',
        'category': 'Enjuagues',
        'disponible': true,
        'mensajeEstado': 'Producto disponible',
        'features': ['Ingredientes naturales', 'Extractos herbales', 'Sin qumicos', 'Sabor natural'],
        'specifications': {'Contenido': '1000ml'}
      },
      {
        'title': 'Oferta Enj 500 + Crema Cuidado Total 90g',
        'price': PriceUtils.formatPriceDisplay('12175'),
        'image': 'assets/ENJUAGES/AMARRECUIDADOTOTAL.png',
        'rating': '5.0',
        'description': 'Cuida tu salud bucal con un sabor fresco y natural',
        'codigoSap': '50360462',
        'category': 'Enjuagues',
        'disponible': true,
        'mensajeEstado': 'Producto disponible',
        'features': ['Especial nios', 'Sabor agradable', 'Sin alcohol', 'Fmula suave'],
        'specifications': {'Contenido': 'Oferta Enj 500 + Crema Cuidado Total 90g'}
      },
      {
        'title': 'Enjuague Bucal Zero 180ml',
        'price': PriceUtils.formatPriceDisplay('4311'),
        'image': 'assets/ENJUAGES/ZERO180.png',
        'rating': '5.0',
        'description': 'Cuida tu salud bucal con un sabor fresco y natural',
        'codigoSap': '50360369',
        'category': 'Enjuagues',
        'disponible': true,
        'mensajeEstado': 'Producto disponible',
        'features': ['Especial nios', 'Sabor agradable', 'Sin alcohol', 'Fmula suave'],
        'specifications': {'Contenido': '180ml'}
      },
      {
        'title': 'Enjuague Bucal Zero 300ml',
        'price': PriceUtils.formatPriceDisplay('6035'),
        'image': 'assets/ENJUAGES/ZERO300.png',
        'rating': '5.0',
        'description': 'Cuida tu salud bucal con un sabor fresco y natural',
        'codigoSap': '50360087',
        'category': 'Enjuagues',
        'disponible': true,
        'mensajeEstado': 'Producto disponible',
        'features': ['Especial nios', 'Sabor agradable', 'Sin alcohol', 'Fmula suave'],
        'specifications': {'Contenido': '300ml'}
      },
      {
        'title': 'Enjuague Bucal Zero 500ml',
        'price': PriceUtils.formatPriceDisplay('8450'),
        'image': 'assets/ENJUAGES/ZERO500.png',
        'rating': '5.0',
        'description': 'Cuida tu salud bucal con un sabor fresco y natural',
        'codigoSap': '50360089',
        'category': 'Enjuagues',
        'disponible': true,
        'mensajeEstado': 'Producto disponible',
        'features': ['Especial nios', 'Sabor agradable', 'Sin alcohol', 'Fmula suave'],
        'specifications': {'Contenido': '500ml'}
      },
      {
        'title': 'Enjuague Bucal Zero 1000ml',
        'price': PriceUtils.formatPriceDisplay('12675'),
        'image': 'assets/ENJUAGES/ZERO1000.png',
        'rating': '5.0',
        'description': 'Cuida tu salud bucal con un sabor fresco y natural',
        'codigoSap': '50360430',
        'category': 'Enjuagues',
        'disponible': true,
        'mensajeEstado': 'Producto disponible',
        'features': ['Especial nios', 'Sabor agradable', 'Sin alcohol', 'Fmula suave'],
        'specifications': {'Contenido': '1000ml'}
      },
      {
        'title': 'Enjuague Bucal 50ml',
        'price': PriceUtils.formatPriceDisplay('2855'),
        'image': 'assets/ENJUAGES/FLUOR30.png',
        'rating': '5.0',
        'description': 'Cuida tu salud bucal con un sabor fresco y natural',
        'codigoSap': '50330019',
        'category': 'Enjuagues',
        'disponible': true,
        'mensajeEstado': 'Producto disponible',
        'features': ['Especial nios', 'Sabor agradable', 'Sin alcohol', 'Fmula suave'],
        'specifications': {'Contenido': '50ml'}
      },
      {
        'title': 'Enjuague Bucal Caja x24',
        'price': PriceUtils.formatPriceDisplay('57085'),
        'image': 'assets/ENJUAGES/FLUORMULTIPLE.png',
        'rating': '5.0',
        'description': 'Cuida tu salud bucal con un sabor fresco y natural',
        'codigoSap': '50360119',
        'category': 'Enjuagues',
        'disponible': true,
        'mensajeEstado': 'Producto disponible',
        'features': ['Especial nios', 'Sabor agradable', 'Sin alcohol', 'Fmula suave'],
        'specifications': {'Contenido': 'Caja x24'}
      },
      {
        'title': 'Enjuague Bucal Fluor 180ml',
        'price': PriceUtils.formatPriceDisplay('4775'),
        'image': 'assets/ENJUAGES/FLUOR180.png',
        'rating': '5.0',
        'description': 'Cuida tu salud bucal con un sabor fresco y natural',
        'codigoSap': '50340052',
        'category': 'Enjuagues',
        'disponible': true,
        'mensajeEstado': 'Producto disponible',
        'features': ['Especial nios', 'Sabor agradable', 'Sin alcohol', 'Fmula suave'],
        'specifications': {'Contenido': '180ml'}
      },
      {
        'title': 'Enjuague Bucal Fluor 300ml',
        'price': PriceUtils.formatPriceDisplay('6685'),
        'image': 'assets/ENJUAGES/FLUOR300.png',
        'rating': '5.0',
        'description': 'Cuida tu salud bucal con un sabor fresco y natural',
        'codigoSap': '50360097',
        'category': 'Enjuagues',
        'disponible': true,
        'mensajeEstado': 'Producto disponible',
        'features': ['Especial nios', 'Sabor agradable', 'Sin alcohol', 'Fmula suave'],
        'specifications': {'Contenido': '300ml'}
      },
      {
        'title': 'Enjuague Bucal Fluor 500ml',
        'price': PriceUtils.formatPriceDisplay('9358'),
        'image': 'assets/ENJUAGES/FLUOR500.png',
        'rating': '5.0',
        'description': 'Cuida tu salud bucal con un sabor fresco y natural',
        'codigoSap': '50360096',
        'category': 'Enjuagues',
        'disponible': true,
        'mensajeEstado': 'Producto disponible',
        'features': ['Especial nios', 'Sabor agradable', 'Sin alcohol', 'Fmula suave'],
        'specifications': {'Contenido': '500ml'}
      },
      {
        'title': 'Enjuague Bucal Fluor 1000ml',
        'price': PriceUtils.formatPriceDisplay('14044'),
        'image': 'assets/ENJUAGES/FLUOR1000.png',
        'rating': '5.0',
        'description': 'Cuida tu salud bucal con un sabor fresco y natural',
        'codigoSap': '50340056',
        'category': 'Enjuagues',
        'disponible': true,
        'mensajeEstado': 'Producto disponible',
        'features': ['Especial nios', 'Sabor agradable', 'Sin alcohol', 'Fmula suave'],
        'specifications': {'Contenido': '1000ml'}
      },
      {
        'title': 'Enjuague Bucal Carbon Activado 180ml',
        'price': PriceUtils.formatPriceDisplay('5760'),
        'image': 'assets/ENJUAGES/CARBON1.png',
        'rating': '5.0',
        'description': 'Cuida tu salud bucal con un sabor fresco y natural',
        'codigoSap': '50360371',
        'category': 'Enjuagues',
        'disponible': true,
        'mensajeEstado': 'Producto disponible',
        'features': ['Especial nios', 'Sabor agradable', 'Sin alcohol', 'Fmula suave'],
        'specifications': {'Contenido': '180ml'}
      },
      {
        'title': 'Enjuague Bucal Carbon Activado 500ml',
        'price': PriceUtils.formatPriceDisplay('11627'),
        'image': 'assets/ENJUAGES/CARBONACTIVADO.png',
        'rating': '5.0',
        'description': 'Cuida tu salud bucal con un sabor fresco y natural',
        'codigoSap': '50360246',
        'category': 'Enjuagues',
        'disponible': true,
        'mensajeEstado': 'Producto disponible',
        'features': ['Especial nios', 'Sabor agradable', 'Sin alcohol', 'Fmula suave'],
        'specifications': {'Contenido': '500ml'}
      },
      {
        'title': 'Oferta Enj 500 + Crema Carbon 90g',
        'price': PriceUtils.formatPriceDisplay('16999'),
        'image': 'assets/ENJUAGES/AMARRECARBON.png',
        'rating': '5.0',
        'description': 'Cuida tu salud bucal con un sabor fresco y natural',
        'codigoSap': '50360464',
        'category': 'Enjuagues',
        'disponible': true,
        'mensajeEstado': 'Producto disponible',
        'features': ['Especial nios', 'Sabor agradable', 'Sin alcohol', 'Fmula suave'],
        'specifications': {'Contenido': 'Oferta Enj 500 + Crema Carbon 90g'}
      },
      {
        'title': 'Enjuague Bucal Cuidado Odontologico 300ML',
        'price': PriceUtils.formatPriceDisplay('20825'),
        'image': 'assets/ENJUAGES/ODONTO.png',
        'rating': '5.0',
        'description': 'Cuida tu salud bucal con un sabor fresco y natural',
        'codigoSap': '50360456',
        'category': 'Enjuagues',
        'disponible': true,
        'mensajeEstado': 'Producto disponible',
        'features': ['Especial nios', 'Sabor agradable', 'Sin alcohol', 'Fmula suave'],
        'specifications': {'Contenido': '300ml'}
      },
    ];
  }

  static List<Map<String, dynamic>> getSedasProducts() {
    return [
      {
        'title': 'Seda Dental Cuidado Total Yerbabuena + Flúor 50m',
        'price': PriceUtils.formatPriceDisplay('5160'),
        'image': 'assets/SEDAS/CUIDADOTOTAL50.png',
        'rating': '5.0',
        'description': 'Deslizamiento suave entre dientes para limpieza profunda',
        'codigoSap': '50270013',
        'category': 'Sedas',
        'disponible': true,
        'mensajeEstado': 'Producto disponible',
        'features': ['Deslizamiento suave', 'Limpieza profunda', 'Resistente', 'Sabor menta'],
        'specifications': {'Contenido': '50m', 'Sabor': 'Yerbabuena', 'Grosor': 'Estndar'}
      },
      {
        'title': 'Seda Dental Cuidado Total Menta + Flúor 30m',
        'price': PriceUtils.formatPriceDisplay('4738'),
        'image': 'assets/SEDAS/1.png',
        'rating': '5.0',
        'description': 'Seda ultra fina para espacios interdentales reducidos',
        'codigoSap': '50270011',
        'category': 'Sedas',
        'disponible': true,
        'mensajeEstado': 'Producto disponible',
        'features': ['Ultra fina', 'Espacios pequeos', 'Suave deslizamiento', 'Sin sabor'],
        'specifications': {'Contenido': '30m', 'Sabor': 'Menta'}
      },
      {
        'title': 'Seda Dental Cuidado Total Yerbabuena + Flúor 30m',
        'price': PriceUtils.formatPriceDisplay('4738'),
        'image': 'assets/SEDAS/CUIDADOTOTAL30.png',
        'rating': '5.0',
        'description': 'Se expande al contacto con saliva para mejor limpieza',
        'codigoSap': '50360206',
        'category': 'Sedas',
        'disponible': true,
        'mensajeEstado': 'Producto disponible',
        'features': ['Expandible', 'Mejor limpieza', 'Adaptable', 'Sabor fresco'],
        'specifications': {'Contenido': '30m', 'Sabor': 'Yerbabuena'}
      },
      {
        'title': 'Seda Dental Dis Individual Cera 100m',
        'price': PriceUtils.formatPriceDisplay('4900'),
        'image': 'assets/SEDAS/SEDACONCERA100.png',
        'rating': '5.0',
        'description': 'Seda impregnada con flúor para proteccin adicional',
        'codigoSap': '50360475',
        'category': 'Sedas',
        'disponible': true,
        'mensajeEstado': 'Producto disponible',
        'features': ['Con flúor', 'Proteccin extra', 'Fortalece esmalte', 'Sabor menta'],
        'specifications': {'Contenido': '100m', 'Sabor': 'Sin sabor'}
      },
      {
        'title': 'Seda Dental Dis Individual Cera 200m',
        'price': PriceUtils.formatPriceDisplay('7708'),
        'image': 'assets/SEDAS/SEDACONCERA200.png',
        'rating': '5.0',
        'description': 'Formato cinta ancha para espacios interdentales amplios',
        'codigoSap': '50360360',
        'category': 'Sedas',
        'disponible': true,
        'mensajeEstado': 'Producto disponible',
        'features': ['Formato cinta', 'Espacios amplios', 'Cobertura mayor', 'Resistente'],
        'specifications': {'Contenido': '200m', 'Sabor': 'Sin sabor'}
      },
      {
        'title': 'Seda Dental Cuidado Total Yerbabuena + Flúor 230m',
        'price': PriceUtils.formatPriceDisplay('11627'),
        'image': 'assets/SEDAS/FLUOR230.png',
        'rating': '5.0',
        'description': 'Dispensador compacto ideal para llevar a cualquier lugar',
        'codigoSap': '50360204',
        'category': 'Sedas',
        'disponible': true,
        'mensajeEstado': 'Producto disponible',
        'features': ['Porttil', 'Dispensador compacto', 'Fcil uso', 'Higinico'],
        'specifications': {'Longitud': '30m', 'Material': 'Nylon encerado', 'Sabor': 'Menta suave', 'Grosor': 'Estndar'}
      },
      {
        'title': 'Seda Dental Cuidado Total Menta + Flúor 230m',
        'price': PriceUtils.formatPriceDisplay('11627'),
        'image': 'assets/SEDAS/FLUOR230.png',
        'rating': '5.0',
        'description': 'Dispensador compacto ideal para llevar a cualquier lugar',
        'codigoSap': '50360208',
        'category': 'Sedas',
        'disponible': true,
        'mensajeEstado': 'Producto disponible',
        'features': ['Porttil', 'Dispensador compacto', 'Fcil uso', 'Higinico'],
        'specifications': {'Contenido': '230m', 'Sabor': 'Menta'}
      },
      {
        'title': 'Seda Dental Con Cera Caja x12',
        'price': PriceUtils.formatPriceDisplay('11757'),
        'image': 'assets/SEDAS/CAJAX12.png',
        'rating': '5.0',
        'description': 'Dispensador compacto ideal para llevar a cualquier lugar',
        'codigoSap': '50360242',
        'category': 'Sedas',
        'disponible': true,
        'mensajeEstado': 'Producto disponible',
        'features': ['Porttil', 'Dispensador compacto', 'Fcil uso', 'Higinico'],
        'specifications': {'Contenido': 'Caja x12', 'Sabor': 'Sin sabor'}
      },
      {
        'title': 'Ristra Seda Dental Con Cera X12',
        'price': PriceUtils.formatPriceDisplay('18812'),
        'image': 'assets/SEDAS/FLUOR230.png',
        'rating': '5.0',
        'description': 'Dispensador compacto ideal para llevar a cualquier lugar',
        'codigoSap': '50360363',
        'category': 'Sedas',
        'disponible': true,
        'mensajeEstado': 'Producto disponible',
        'features': ['Porttil', 'Dispensador compacto', 'Fcil uso', 'Higinico'],
        'specifications': {'Contenido': 'Ristra Seda Dental Con Cera X12', 'Sabor': 'Sin sabor'}
      },
    ];
  }

  static List<Map<String, dynamic>> getUniversoNinosProducts() {
    return [
      {
        'title': 'Cepillo Original Flex',
        'price': PriceUtils.formatPriceDisplay('1280'),
        'image': 'assets/NIOS/ORIGINALFLEXNINOS.png',
        'rating': '5.0',
        'description': 'Cepillo con forma flexible para un mejor ajuste',
        'codigoSap': '50360407',
        'codigoSapAlternativo': '50360408',
        'textura': 'Nio',
        'texturaAlternativa': 'Nia',
        'hasTextureOptions': true,
        'category': 'Universo Nios',
        'disponible': true,
        'mensajeEstado': 'Producto disponible',
        'features': ['Cepillo Original Flex'],
        'specifications': {'Contenido': 'Cepillo Original Flex', 'Edad': '3-8 aos'}
      },
      {
        'title': 'Cepillo Children',
        'price': PriceUtils.formatPriceDisplay('1790'),
        'image': 'assets/NIOS/CHILDREN.png',
        'rating': '5.0',
        'description': 'cerdas ultra suaves',
        'codigoSap': '50360090',
        'category': 'Universo Nios',
        'disponible': true,
        'mensajeEstado': 'Producto disponible',
        'features': ['Cepillo Children'],
        'specifications': {'Incluye': 'Solo cepillo'}
      },
      {
        'title': 'Cepillo Junior',
        'price': PriceUtils.formatPriceDisplay('3114'),
        'image': 'assets/NIOS/CEPILLOJUNIOR.png',
        'rating': '5.0',
        'description': 'Pasta dental con delicioso sabor a fresa, sin flúor',
        'codigoSap': '50360108',
        'category': 'Universo Nios',
        'disponible': true,
        'mensajeEstado': 'Producto disponible',
        'specifications': {'Contenido': 'Cepillo Junior'}
      },
      {
        'title': 'Cepillo kids Bonite',
        'price': PriceUtils.formatPriceDisplay('3527'),
        'image': 'assets/NIOS/CEPILLOBONITE.png',
        'rating': '5.0',
        'description': 'Cepillo kids Bonite',
        'codigoSap': '51370004',
        'category': 'Universo Nios',
        'disponible': true,
        'mensajeEstado': 'Producto disponible',
        'features': ['Tema universo'],
        'specifications': {'Edad': '4-10 aos'}
      },
      {
        'title': 'Kit Gold Nio',
        'price': PriceUtils.formatPriceDisplay('5879'),
        'image': 'assets/NIOS/GOLNIO.png',
        'rating': '5.0',
        'description': 'Kit Gold Nio',
        'codigoSap': '50280130',
        'codigoSapAlternativo': '50360200',
        'textura': 'Nio',
        'texturaAlternativa': 'Nia',
        'hasTextureOptions': true,
        'category': 'Universo Nios',
        'disponible': true,
        'mensajeEstado': 'Producto disponible',
        'features': ['Kit Gold Nio'],
        'specifications': {'Edad': '6+ aos'}
      },
      {
        'title': 'Cepillo Baby Panda',
        'price': PriceUtils.formatPriceDisplay('6401'),
        'image': 'assets/NIOS/BABYPANDA.png',
        'rating': '5.0',
        'description': 'Cepillo Baby Panda',
        'codigoSap': '50360203',
        'category': 'Universo Nios',
        'disponible': true,
        'mensajeEstado': 'Producto disponible',
        'features': ['Tema universo'],
        'specifications': {'Edad': '0-3 aos'}
      },
      {
        'title': 'Kit Junior',
        'price': PriceUtils.formatPriceDisplay('6467'),
        'image': 'assets/NIOS/KITJUNIOR.png',
        'rating': '5.0',
        'description': 'Cepillo Baby Panda',
        'codigoSap': '50360089',
        'category': 'Universo Nios',
        'disponible': true,
        'mensajeEstado': 'Producto disponible',
        'features': ['Tema universo'],
        'specifications': {}
      },
      {
        'title': 'Cepillo Space Duo Nio + Cremas 30gr',
        'price': PriceUtils.formatPriceDisplay('10425'),
        'image': 'assets/NIOS/SPACEDUO.png',
        'rating': '5.0',
        'description': 'Cepillo Baby Panda',
        'codigoSap': '50280010',
        'category': 'Universo Nios',
        'disponible': true,
        'mensajeEstado': 'Producto disponible',
        'features': ['Tema universo'],
        'specifications': {}
      },
      {
        'title': 'Kit viajero',
        'price': PriceUtils.formatPriceDisplay('11627'),
        'image': 'assets/NIOS/KITNIOS.png',
        'rating': '5.0',
        'description': 'Kit viajero',
        'codigoSap': '50280053',
        'category': 'Universo Nios',
        'disponible': true,
        'mensajeEstado': 'Producto disponible',
        'features': ['Tema universo'],
        'specifications': {'Contenido': 'Kit viajero'}
      },
      {
        'title': 'Crema dental tutti-frutti sin fluor 70g',
        'price': PriceUtils.formatPriceDisplay('6205'),
        'image': 'assets/NIOS/CREMANINOS.png',
        'rating': '5.0',
        'description': 'Kit viajero',
        'codigoSap': '50340012',
        'category': 'Universo Nios',
        'disponible': true,
        'mensajeEstado': 'Producto disponible',
        'features': ['Tema universo'],
        'specifications': {'Contenido': 'Crema dental tutti-frutti sin fluor 70g'}
      },
      {
        'title': 'Crema dental chicle sin fluor 70g',
        'price': PriceUtils.formatPriceDisplay('6205'),
        'image': 'assets/NIOS/SINFLUOR.png',
        'rating': '5.0',
        'description': 'Kit viajero',
        'codigoSap': '50340014',
        'category': 'Universo Nios',
        'disponible': true,
        'mensajeEstado': 'Producto disponible',
        'features': ['Tema universo'],
        'specifications': {'Contenido': 'Kit viajero'}
      },
      {
        'title': 'Enjuague bucal tutti frutti 300ml',
        'price': PriceUtils.formatPriceDisplay('6467'),
        'image': 'assets/NIOS/TUTTI300.png',
        'rating': '5.0',
        'description': 'Kit viajero',
        'codigoSap': '50360107',
        'category': 'Universo Nios',
        'disponible': true,
        'mensajeEstado': 'Producto disponible',
        'features': ['Tema universo'],
        'specifications': {'Contenido': 'Enjuague bucal tutti frutti 300ml'}
      },
      {
        'title': 'Enjuague bucal chicle 300ml',
        'price': PriceUtils.formatPriceDisplay('6467'),
        'image': 'assets/NIOS/NIOS300.png',
        'rating': '5.0',
        'description': 'Kit viajero',
        'codigoSap': '50360106',
        'category': 'Universo Nios',
        'disponible': true,
        'mensajeEstado': 'Producto disponible',
        'features': ['Tema universo'],
        'specifications': {'Contenido': 'Enjuague bucal chicle 300ml'}
      },
      {
        'title': 'Crema dental chicle sin fluor + Cep 30g',
        'price': PriceUtils.formatPriceDisplay('4507'),
        'image': 'assets/NIOS/CREMADENTALCHICLE.png',
        'rating': '5.0',
        'description': 'Kit viajero',
        'codigoSap': '50360368',
        'category': 'Universo Nios',
        'disponible': true,
        'mensajeEstado': 'Producto disponible',
        'features': ['Tema universo'],
        'specifications': {'Contenido': 'Crema dental chicle sin fluor + Cep 30g'}
      },
      {
        'title': 'Crema dental tutti-frutti sin fluor + Cep 30g',
        'price': PriceUtils.formatPriceDisplay('4507'),
        'image': 'assets/NIOS/CREMASINFLUORNINA.png',
        'rating': '5.0',
        'description': 'Kit viajero',
        'codigoSap': '50360367',
        'category': 'Universo Nios',
        'disponible': true,
        'mensajeEstado': 'Producto disponible',
        'features': ['Tema universo'],
        'specifications': {'Contenido': 'Crema dental tutti-frutti sin fluor + Cep 30g'}
      },
      {
        'title': 'Crema dental con fluor 30g + Cep junior',
        'price': PriceUtils.formatPriceDisplay('4507'),
        'image': 'assets/NIOS/OFERTAJUNIOR.png',
        'rating': '5.0',
        'description': 'Kit viajero',
        'codigoSap': '50360474',
        'category': 'Universo Nios',
        'disponible': true,
        'mensajeEstado': 'Producto disponible',
        'features': ['Tema universo'],
        'specifications': {'Contenido': 'Crema dental con fluor 30g + Cep junior'}
      }
    ];
  }

  static List<Map<String, dynamic>> getKitsProducts() {
    return [
      {
        'title': 'Kit Economico',
        'price': PriceUtils.formatPriceDisplay('11836'),
        'image': 'assets/KITS/VIAJERO.png',
        'rating': '5.0',
        'description': 'Todo lo necesario para higiene bucal completa y profesional',
        'codigoSap': '50360209',
        'codigoSapAlternativo': '50360210',
        'textura': 'Media',
        'texturaAlternativa': 'Suave',
        'hasTextureOptions': true,
        'category': 'Kits',
        'disponible': true,
        'mensajeEstado': 'Producto disponible',
        'features': ['Kit completo', 'Calidad premium', 'Estuche de viaje', 'Productos profesionales'],
        'specifications': {'Contenido': 'Kit Economico'}
      },
      {
        'title': 'Kit Higiene Viajero',
        'price': PriceUtils.formatPriceDisplay('14174'),
        'image': 'assets/KITS/KITIGIENEORAL.png',
        'rating': '5.0',
        'description': 'Sistema completo de blanqueamiento para uso en casa',
        'codigoSap': '50340039',
        'codigoSapAlternativo': '50360376',
        'textura': 'Media',
        'texturaAlternativa': 'Suave',
        'hasTextureOptions': true,
        'category': 'Kits',
        'disponible': true,
        'mensajeEstado': 'Producto disponible',
        'features': ['Blanqueamiento profesional', 'Resultados visibles', 'Uso en casa', 'Seguro y efectivo'],
        'specifications': {'Incluye': 'Gel blanqueador, cubetas, pasta'}
      },
      {
        'title': 'Kit Higiene Viajero Cuidado Total',
        'price': PriceUtils.formatPriceDisplay('19465'),
        'image': 'assets/KITS/TOTALCERRADO.png',
        'rating': '5.0',
        'description': 'Solucin completa para dientes sensibles con alivio inmediato',
        'codigoSap': '50290010',
        'codigoSapAlternativo': '50290011',
        'textura': 'Media',
        'texturaAlternativa': 'Suave',
        'hasTextureOptions': true,
        'category': 'Kits',
        'disponible': true,
        'mensajeEstado': 'Producto disponible',
        'features': ['Para sensibilidad', 'Alivio inmediato', 'Proteccin 24h', 'Fmulas suaves'],
        'specifications': {'Incluye': 'Pasta, enjuague, cepillo suave'}
      },
    ];
  }
}
