services:
  pedidos-backend:
    build: .
    container_name: pedidos-backend
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - PORT=3000
      - REDIS_URL=redis://pedidos-redis:6379
    depends_on:
      - pedidos-redis

  pedidos-redis:
    image: redis:7-alpine
    container_name: pedidos-redis
    restart: always
    command: redis-server --maxmemory 128mb --maxmemory-policy allkeys-lru --save ""
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 3s
      retries: 3
